# Generated by Django 3.1.2 on 2020-10-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korea_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Korea_total_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalCase', models.IntegerField()),
                ('TotalDeath', models.IntegerField()),
                ('TotalRecovered', models.IntegerField()),
                ('NowCase', models.IntegerField()),
            ],
        ),
    ]
